Added Mk2 wrist folder
robotology/icub-firmware-models pull request #22
Opened 2023-03-16 08:54 UTC by ale-git

Contains:
- Simmechanics model
- Simulink control system configured for decoupler embedded code generation
- Mathematics of spherical wrist documentation

2023-03-16 15:49 UTC, pattacini requested changes
Nice work @ale-git, especially the description of the underlying maths.

I've got a couple of suggestions:
- It'd be nice to segregate all the step files into a dedicated subfolder.
- Having a MATLAB project to click on to get everything started is a very convenient practice. This way, one already knows what to do when landing here.
- The README should also contain a brief section on code generation, especially for what regards the difference between the left and the right wrist.

2023-03-16 15:49 UTC, pattacini commented on wrist_mk2/README.md
> +-   In the case of symmetrical structure, the coordinates of the platform joints in the rest configuration are $q_1=(1,0,0)$, $q_2=(-\frac{1}{2},\frac{\sqrt{3}}{2},0)$ e $q_3=(-\frac{1}{2},-\frac{\sq
```suggestion
-   In the case of symmetrical structure, the coordinates of the platform joints in the rest configuration are $q_1=(1,0,0)$, $q_2=(-\frac{1}{2},\frac{\sqrt{3}}{2},0)$ and $q_3=(-\frac{1}{2},-\frac{\sqrt{3}}{2},0)$
```

2023-03-16 15:49 UTC, pattacini commented on wrist_mk2/platform_wris_-60_50_prt.step
the name seems missing the ending `t`.

2023-03-17 13:27 UTC, pattacini commented
This is a PR relevant to @marcoaccame @sgiraz @mfussi66.

/remind in 7 days to clean up our internal repo of physical models

2023-03-24 21:45 UTC, ale-git commented
I'm closing and reastarting since the workflow is messed up because of missing lfs management.

2023-03-24 21:45 UTC, closed without merging

2023-03-25 08:56 UTC, pattacini commented
Follow-up in #26