LuGre friction model implementation
robotology/icub-firmware-models pull request #97
Opened 2024-10-22 12:49 UTC by ale-git

The LuGre friction model has been implemented in SImulink, ready for automatic code generation.
The output code is included in icub-firmware to add sensorless torque estimation capabilities to the control boards.

2024-10-22 13:16 UTC, pattacini commented
Thanks @ale-git for the contribution 👍🏻 
I'll be reviewing the PR in the next few days.

2024-10-23 06:28 UTC, pattacini commented
Hi @ale-git 

What's the strategy behind parsing the LuGre params?
Ideally, to provide back-compatibility (quite important here), if the section is not found then the SW should NOT make use of the LuGre.

2024-10-27 10:14 UTC, pattacini requested changes
Hi @ale-git 

Before merging this PR, we need to address several points.

### Documentation
- The state equations is not correct.
- Missing details on $`g\left(v\right)`$.
- It'd be appropriate to cite a paper on LuGre, e.g. DOI: 10.1109/mcs.2008.929425.
- Nothing is said about how to tune the LuGre params. This is fundamental to make it usable.

### Implementation
- Especially when a dynamic is at stake, it's much better to resort to Simulink rather than MATLAB code. We already have an internal LuGre implementation in Simulink that I can refer you to[^1].
- Most of the time $`\sigma_1`$ is related to $`\sigma_0`$.
- The model interface can be improved.

### MATLAB Project
The project has to be fine-tuned, although this is the very last thing.

---

I propose to set up a meeting for this 🗓️

[^1]: It looks like this:

      ![image](https://github.com/user-attachments/assets/bf1b40de-1233-4051-9c24-c9daa59c6342)

2024-10-29 15:58 UTC, ale-git commented
I commited the wrong README.md file, whose right version was deleted instead (fixed).
I also added a couple figures.

2024-11-05 13:10 UTC, pattacini commented
Any update on this?

2024-11-06 16:35 UTC, ale-git commented
I've added the Simulink-block made torque estimator to the model.
![image](https://github.com/user-attachments/assets/ab45cd6a-eb68-41d1-89c0-150e31c804dd)

2024-11-07 07:53 UTC, pattacini commented
Great!
There were other things to address we discussed last week.
I'll give the PR the last touch when the work is complete.

2024-11-21 08:10 UTC, pattacini commented
Hi @ale-git 

We still need to address the following important point:

>Nothing is said about how to tune the LuGre params. This is fundamental to make it usable.

2024-12-05 07:45 UTC, pattacini requested changes
Hi @ale-git 

Thanks for the notes on how to tune the params.
I've dropped some inline suggestions you may incorporate straight away.

A couple of important points though:
- Nothing is said about the math underlying the brute force estimation. I think that we ought to outline the principle beneath at least, in a brief paragraph.
- I would report the measurement units along with the values.

2024-12-05 07:45 UTC, pattacini commented on sensorless_torque/README.md
> +[param_estimator.m](param_estimator.m)
```suggestion
An automatic parameter estimation tool is provided:
- [`param_estimator.m`](param_estimator.m)
```

2024-12-05 07:45 UTC, pattacini commented on sensorless_torque/README.md
> +![Input filepath](assets/filepath.png)
```suggestion
![Input filepath](assets/FilePath.png)
```

2024-12-05 07:45 UTC, pattacini commented on sensorless_torque/README.md
> +3.  S0, S1 (LuGre hysteresis model stiffness and damping).
```suggestion
1.  `Km` (motor torque constant), `Kw` (viscous friction constant), `Fc` (Coulomb force constant);
2.  `Fs` (Stribeck force constant), `Vth` (Stribeck force velocity threshold);
3.  `S0`, `S1` (LuGre hysteresis model stiffness and damping).
```

This formatting helps highlight variables within the text.

2024-12-05 07:45 UTC, pattacini commented on sensorless_torque/README.md
> +The search space must be initially limited in some way, thus the Km torque constant, Kw viscous friction constant and Fc Coulomb force constant initial ranges are restricted to 1/5 to 5x the values m
```suggestion
The search space must be initially limited in some way, thus the `Km` torque constant, `Kw` viscous friction constant and `Fc` Coulomb force constant initial ranges are restricted to 1/5x to 5x the values measured in the ergoCub new medium joint, covering in this way a wide range of present and future joint sizes.
```

2024-12-05 07:45 UTC, pattacini commented on sensorless_torque/README.md
> +4.  measured joint torque [Nm], joint side.
```suggestion
1.  time [s];
2.  measured current [A];
3.  measured velocity [rad/s], motor side;
4.  measured joint torque [Nm], joint side.
```

2024-12-05 07:45 UTC, pattacini commented on sensorless_torque/README.md
> +The data source experiment should be in some way meaningful, i.e. with typical velocity and torque back and forth motion cycles, duration > 20 s, about 1 kHz sampling.
```suggestion
The data source experiment should be in some way meaningful: i.e., undergoing typical velocity and torque, back and forth motion cycles, time duration > 20 s, about 1 kHz sample rate. 
```

2024-12-05 07:45 UTC, pattacini commented on sensorless_torque/assets/Output.png
I think it's important to output the measurements units too.

2024-12-05 10:11 UTC, ale-git commented
I've made the requested changes

2024-12-05 11:03 UTC, pattacini approved these changes
Thanks!

2024-12-05 11:04 UTC, merged